# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/seanballais/Code/Throwaway/MLFQSimApp/MLFQSimApp/appwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AppWindow(object):
    def setupUi(self, AppWindow):
        AppWindow.setObjectName("AppWindow")
        AppWindow.resize(800, 600)
        AppWindow.setMinimumSize(QtCore.QSize(800, 600))
        AppWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtWidgets.QWidget(AppWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.processLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.processLayout.setContentsMargins(11, 11, 11, 11)
        self.processLayout.setSpacing(6)
        self.processLayout.setObjectName("processLayout")
        self.processSettingsLayout = QtWidgets.QVBoxLayout()
        self.processSettingsLayout.setContentsMargins(11, 11, 11, 11)
        self.processSettingsLayout.setSpacing(6)
        self.processSettingsLayout.setObjectName("processSettingsLayout")
        self.scheduleProcessesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scheduleProcessesLabel.setFont(font)
        self.scheduleProcessesLabel.setObjectName("scheduleProcessesLabel")
        self.processSettingsLayout.addWidget(self.scheduleProcessesLabel)
        self.schedulingAlgorithmSelection = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.schedulingAlgorithmSelection.setObjectName("schedulingAlgorithmSelection")
        self.schedulingAlgorithmSelection.addItems((
            'First Come, First Serve',
            'Shortest Job First',
            'Shortest Remaining Time First',
            'Non-Preemtive Priority',
            'Pre-emptive Priority',
            'Round Robin'
        ))
        self.processSettingsLayout.addWidget(self.schedulingAlgorithmSelection)
        self.scheduleButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.scheduleButton.setObjectName("scheduleButton")
        self.processSettingsLayout.addWidget(self.scheduleButton)
        self.additionTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.additionTitle.setFont(font)
        self.additionTitle.setObjectName("additionTitle")
        self.processSettingsLayout.addWidget(self.additionTitle)
        self.processIDLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.processIDLabel.setObjectName("processIDLabel")
        self.processSettingsLayout.addWidget(self.processIDLabel)
        self.processIDTextbox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.processIDTextbox.setObjectName("processIDTextbox")
        self.processSettingsLayout.addWidget(self.processIDTextbox)
        self.arrivalTimeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.arrivalTimeLabel.setObjectName("arrivalTimeLabel")
        self.processSettingsLayout.addWidget(self.arrivalTimeLabel)
        self.arrivalTimeTextbox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.arrivalTimeTextbox.setObjectName("arrivalTimeTextbox")
        self.processSettingsLayout.addWidget(self.arrivalTimeTextbox)
        self.burstTimeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.burstTimeLabel.setObjectName("burstTimeLabel")
        self.processSettingsLayout.addWidget(self.burstTimeLabel)
        self.burstTimeTextbox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.burstTimeTextbox.setObjectName("burstTimeTextbox")
        self.processSettingsLayout.addWidget(self.burstTimeTextbox)
        self.priorityLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.priorityLabel.setObjectName("priorityLabel")
        self.processSettingsLayout.addWidget(self.priorityLabel)
        self.priorityTextbox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.priorityTextbox.setObjectName("priorityTextbox")
        self.processSettingsLayout.addWidget(self.priorityTextbox)
        self.addNewProcessButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addNewProcessButton.setObjectName("addNewProcessButton")
        self.processSettingsLayout.addWidget(self.addNewProcessButton)
        self.deleteProcessLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deleteProcessLabel.setFont(font)
        self.deleteProcessLabel.setObjectName("deleteProcessLabel")
        self.processSettingsLayout.addWidget(self.deleteProcessLabel)
        self.deleteProcessIDLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.deleteProcessIDLabel.setObjectName("deleteProcessIDLabel")
        self.processSettingsLayout.addWidget(self.deleteProcessIDLabel)
        self.deletePIDTextbox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.deletePIDTextbox.setObjectName("deletePIDTextbox")
        self.processSettingsLayout.addWidget(self.deletePIDTextbox)
        self.deleteProcessButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deleteProcessButton.setObjectName("deleteProcessButton")
        self.processSettingsLayout.addWidget(self.deleteProcessButton)
        self.processLayout.addLayout(self.processSettingsLayout)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(259, 0, 541, 411))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.chartLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.chartLayout.setContentsMargins(11, 11, 11, 11)
        self.chartLayout.setSpacing(6)
        self.chartLayout.setObjectName("chartLayout")
        self.chartScrollArea = QtWidgets.QScrollArea(self.horizontalLayoutWidget)
        self.chartScrollArea.setWidgetResizable(True)
        self.chartScrollArea.setObjectName("chartScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 537, 407))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.chartHolder = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.chartHolder.setGeometry(QtCore.QRect(2, 5, 501, 391))
        self.chartHolder.setAlignment(QtCore.Qt.AlignCenter)
        self.chartHolder.setObjectName("chartHolder")
        self.chartScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.chartLayout.addWidget(self.chartScrollArea)
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 410, 541, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.processTableLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.processTableLayout.setContentsMargins(11, 11, 11, 11)
        self.processTableLayout.setSpacing(6)
        self.processTableLayout.setObjectName("processTableLayout")
        self.processTableLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.processTableLabel.setFont(font)
        self.processTableLabel.setObjectName("processTableLabel")
        self.processTableLayout.addWidget(self.processTableLabel)
        self.processTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.processTable.setObjectName("processTable")
        self.processTable.setColumnCount(4)
        self.processTable.setRowCount(0)
        self.processTable.setHorizontalHeaderLabels('Process;Arrival Time;Burst Time;Priority'.split(';'))
        self.processTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.processTableLayout.addWidget(self.processTable)
        AppWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(AppWindow)
        QtCore.QMetaObject.connectSlotsByName(AppWindow)

    def retranslateUi(self, AppWindow):
        _translate = QtCore.QCoreApplication.translate
        AppWindow.setWindowTitle(_translate("AppWindow", "Multi-Level Feedback Queue Simulator"))
        self.scheduleProcessesLabel.setText(_translate("AppWindow", "Schedule Processes"))
        self.scheduleButton.setText(_translate("AppWindow", "Schedule Processes"))
        self.additionTitle.setText(_translate("AppWindow", "Add A New Process"))
        self.processIDLabel.setText(_translate("AppWindow", "Process ID"))
        self.arrivalTimeLabel.setText(_translate("AppWindow", "Arrival Time"))
        self.burstTimeLabel.setText(_translate("AppWindow", "Burst Time"))
        self.priorityLabel.setText(_translate("AppWindow", "Priority"))
        self.addNewProcessButton.setText(_translate("AppWindow", "Add process"))
        self.deleteProcessLabel.setText(_translate("AppWindow", "Delete A Process"))
        self.deleteProcessIDLabel.setText(_translate("AppWindow", "Process ID"))
        self.deleteProcessButton.setText(_translate("AppWindow", "Delete process"))
        self.chartHolder.setText(_translate("AppWindow", "The schedule of your processes will appear here."))
        self.processTableLabel.setText(_translate("AppWindow", "Processes"))

